import AppKit
import Carbon.HIToolbox
import CryptoKit
import Vision

/// Reading from, writing to, and pasting with the system pasteboard.
enum Clipboard {
    /// Types apps use to say "don't record this" (see nspasteboard.org).
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
    ]
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "com.agilebits.onepassword",
    ]
    private static let secretPrefixes = [
        "sk-", "sk_live_", "rk_live_", "ghp_", "gho_", "ghs_", "github_pat_",
        "glpat-", "xoxb-", "xoxp-", "AKIA", "AIza",
    ]

    static func shouldIgnore(_ types: [NSPasteboard.PasteboardType], skipConcealed: Bool) -> Bool {
        types.isEmpty || types.contains {
            transientTypes.contains($0.rawValue) || (skipConcealed && concealedTypes.contains($0.rawValue))
        }
    }

    /// Private keys, well-known API token formats and card numbers.
    static func looksSensitive(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.hasPrefix("-----BEGIN"), trimmed.contains("PRIVATE KEY") { return true }
        if isCardNumber(trimmed) { return true }
        return (20...300).contains(trimmed.utf8.count)
            && !trimmed.contains(where: \.isWhitespace)
            && secretPrefixes.contains(where: trimmed.hasPrefix)
    }

    private static func isCardNumber(_ text: String) -> Bool {
        guard text.utf8.count <= 23,
              text.allSatisfy({ $0.isASCII && ($0.isNumber || $0 == " " || $0 == "-") }) else { return false }
        let digits = text.compactMap(\.wholeNumberValue)
        guard (13...19).contains(digits.count) else { return false }
        let sum = digits.reversed().enumerated().reduce(0) { sum, pair in
            let doubled = pair.offset.isMultiple(of: 2) ? pair.element : pair.element * 2
            return sum + (doubled > 9 ? doubled - 9 : doubled)
        }
        return sum.isMultiple(of: 10)
    }

    static func fileURLs(_ pasteboard: NSPasteboard) -> [URL]? {
        let urls = pasteboard.readObjects(
            forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]
        ) as? [URL]
        return urls?.isEmpty == false ? urls : nil
    }

    static func image(_ pasteboard: NSPasteboard) -> (data: Data, isPNG: Bool)? {
        if let png = pasteboard.data(forType: .png) { return (png, true) }
        if let tiff = pasteboard.data(forType: .tiff) { return (tiff, false) }
        return nil
    }

    @MainActor
    static func write(_ item: ClipItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.kind {
        case .image:
            if let name = item.image, let data = try? Data(contentsOf: ImageStore.url(name)) {
                pasteboard.setData(data, forType: .png)
            }
        case .files:
            pasteboard.writeObjects((item.files ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        default:
            pasteboard.setString(item.text, forType: .string)
        }
        if item.isLocked {
            // Ask other clipboard tools not to record it.
            pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        }
    }

    @MainActor
    static func write(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    // MARK: - Pasting into other apps

    static var canPaste: Bool { AXIsProcessTrusted() }

    /// Adds ClipBar to the Accessibility list and opens that pane of System Settings.
    static func requestPastePermission() {
        _ = AXIsProcessTrustedWithOptions(["AXTrustedCheckOptionPrompt": true] as CFDictionary)
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
            NSWorkspace.shared.open(url)
        }
    }

    static func pressPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        for keyDown in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: keyDown)
            event?.flags = .maskCommand
            event?.post(tap: .cgSessionEventTap)
        }
    }
}

/// Copied images live as PNG files named after their hash, so duplicates share one file.
enum ImageStore {
    @MainActor private static let thumbnails = NSCache<NSString, NSImage>()

    static func url(_ name: String) -> URL {
        Paths.images.appending(path: name)
    }

    static func store(_ data: Data, isPNG: Bool) -> String? {
        guard let png = isPNG ? data : NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
        else { return nil }
        let name = SHA256.hash(data: png).prefix(16).map { String(format: "%02x", $0) }.joined() + ".png"
        let url = url(name)
        if !FileManager.default.fileExists(atPath: url.path) {
            guard (try? png.write(to: url, options: .atomic)) != nil else { return nil }
        }
        return name
    }

    @MainActor
    static func thumbnail(_ name: String) -> NSImage? {
        if let cached = thumbnails.object(forKey: name as NSString) { return cached }
        let options = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 96,
        ] as CFDictionary
        guard let source = CGImageSourceCreateWithURL(url(name) as CFURL, nil),
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options) else { return nil }
        let thumbnail = NSImage(cgImage: image, size: .zero)
        thumbnails.setObject(thumbnail, forKey: name as NSString)
        return thumbnail
    }

    static func recognizeText(_ name: String) async -> String {
        var request = RecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.automaticallyDetectsLanguage = true
        guard let observations = try? await request.perform(on: url(name)) else { return "" }
        // Low-confidence hits are mostly icons and glyphs read as stray characters.
        return observations
            .compactMap { $0.topCandidates(1).first }
            .filter { $0.confidence >= 0.5 }
            .map(\.string)
            .joined(separator: "\n")
    }

    static func delete(_ names: some Sequence<String>) {
        for name in names { try? FileManager.default.removeItem(at: url(name)) }
    }

    static func purge(keeping names: Set<String>) {
        let files = (try? FileManager.default.contentsOfDirectory(atPath: Paths.images.path)) ?? []
        delete(files.filter { !names.contains($0) })
    }
}

/// Cached app and file icons.
@MainActor
enum Icons {
    struct App {
        let name: String
        let icon: NSImage
    }

    private static var apps: [String: App?] = [:]
    private static let files = NSCache<NSString, NSImage>()

    static func app(_ bundleID: String?) -> App? {
        guard let bundleID else { return nil }
        if let cached = apps[bundleID] { return cached }
        let app = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID).map { url in
            let name = FileManager.default.displayName(atPath: url.path)
            return App(
                name: name.hasSuffix(".app") ? String(name.dropLast(4)) : name,
                icon: NSWorkspace.shared.icon(forFile: url.path)
            )
        }
        apps[bundleID] = app
        return app
    }

    static func file(_ path: String) -> NSImage {
        if let cached = files.object(forKey: path as NSString) { return cached }
        let icon = NSWorkspace.shared.icon(forFile: path)
        files.setObject(icon, forKey: path as NSString)
        return icon
    }
}
